### ISSUE TITLE
Add setting for custom .git path

### ISSUE THREAD

**Issue by mfp22** [gkotas/vscode-restore-git-branch-tabs#2]
My TypeScript app is part of a bigger git project and the `.git` folder is in the folder 3 levels above the folder that I want to have open in VSCode. It would be really nice to have a workspace setting that allowed me to specify a custom path to `.git`.

**Comment by gkotas** [comment]
I also ran into this. The biggest issue with this is that VSCode needs the files in the workspace in order to be able to watch them.

**Comment by gkotas** [comment]
I have added this option in v0.4.1

**Comment by aliaksandrsen** [comment]
My TypeScript app is part of a bigger git project and the .git folder is in the folder 3 levels above the folder that I want to have open in VSCode. It would be really nice to have a workspace setting that allowed me to specify a custom path to .git.

This not work.
