### ISSUE TITLE
Tabs close when creating a commit on a detached HEAD

### ISSUE THREAD

**Issue by mbrookes** [gkotas/vscode-restore-git-branch-tabs#3]
We use https://www.npmjs.com/package/git-pull-request to open 3rd-party PRs on a detached head. 

When making a commit in order to push changes back to the remote (e.g `gpr -p github-user:thier-branch`, the open tabs are closed.

**Comment by gkotas** [comment]
Does turning on the New Branch Preserve Tabs option fix this?

**Comment by mbrookes** [comment]
Yep, thanks!
