### ISSUE TITLE
Breaking Source Control?

### ISSUE THREAD

**Issue by Flexa-B** [gkotas/vscode-restore-git-branch-tabs#4]
Hi there,

So, I use the SVN source control ext. for work, and today I open VSCode to see that none of my source control is working, and that my source control menus can't find the remote repository. After a long morning of digging, I decide to disable the extensions one by one as a last resort.

After testing, it turns out that just disabling this ext. made it so all of my source control works like it use to. Not sure how this could happen, but I did see a new release of this ext. was pushed out on the 17th, so I thought it might be something with this.

Let me know if you want any further info to look into this problem. Thanks!

**Comment by gkotas** [comment]
It is entirely possible it was something I changed in the latest release as I have very little knowledge of what I am doing and don't really test it much. If it works for me, I publish it.

Anyway, can you trying installing the older version and confirming it works then. Click the gear and Install another version v0.3.0.

**Comment by Flexa-B** [comment]
Not a problem. I have tested and confirmed its only an issues when I have v0.4.0 installed. I have included screenshots for reference with private info removed.

v0.3.0 Source Control Panel
![v0.3.0 Source Control Panel](https://imgur.com/FQ8baEP.png)

v0.3.0 Subverison Panel
![v0.3.0 Subverison Panel](https://imgur.com/cnaYTWZ.png)

v0.4.0 Source Control Panel
![v0.4.0 Source Control Panel](https://imgur.com/jDaLoUD.png)

v0.4.0 Subverison Panel
![v0.4.0 Subverison Panel](https://imgur.com/67uaGCa.png)

I use subverison for work, so it's not really an issue to uninstall or use an older version, so no worries if you can't fix it, more of a FYI.

**Comment by gkotas** [comment]
I have changed the way I detect git repos. Let me know if v0.4.1 works.

**Comment by Flexa-B** [comment]
It looks like it fixed my issues. Thanks!
